### PR TITLE
numericPrecision option added to pws-current files

### PR DESCRIPTION
**Pull request by jimison**
Per issue #8, added numericPrecision option to allow decimal results for various values returned by the API request.

### CODE REVIEW

**Comment by johnwalicki** [comment]
@jimison  - this patch looks great. Thank you!

I'm testing it. Re-reading the docs at https://ibm.co/v2PWSCC

What is your use case for extra precision?

**Comment by johnwalicki** [comment]
<h3 dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" id="docs-internal-guid-b547f238-7fff-046c-0206-2f313d4ecbfb"><span style="font-size:11pt;font-family:Cambria,serif;color:#4f81bd;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Valid Parameter Definitions</span></h3><div dir="ltr" style="margin-left:0pt;" align="left">

Parameter Name | Valid Parameter Value | Description
-- | -- | --
numericPrecision | decimal | Optional parameter.  Set to ‘decimal’ to ensure data is returned in decimal format when needed.  Will return integers if this value is not used.

</div>

**Comment by jimison** [comment]
I'm comparing temperatures from various sources, including RPi's and
DB18S20 sensors (https://datasheets.maximintegrated.com/en/ds/DS18S20.pdf)
for actionable events and notifications. I want the extra precision as long
as there's not a polling time trade-off. This API is super handy since my
Weather Station posts updates every 5 seconds.

**Comment by johnwalicki** [comment]
Without `&numericPrecision=decimal`
```
{"temp":-1,"heatIndex":-1,"dewpt":-17,"windChill":-6,"windSpeed":14,"windGust":18,"pressure":998.71,"precipRate":0,"precipTotal":0,"elev":37}
```
With `&numericPrecision=decimal`
```
{"temp":-1.2,"heatIndex":-1.2,"dewpt":-16.2,"windChill":-3.9,"windSpeed":7.2,"windGust":11.1,"pressure":998.92,"precipRate":0,"precipTotal":0,"elev":36.9}
```

**Comment by johnwalicki** [comment]
Thanks for reading the TWC docs and adding this optional parameter.
Merging the PR
I will update the changelog, spin a new release, push it to NPM.  Good reason to rebase any outdated dependencies too.

**Comment by johnwalicki** [comment]
@jimison  - I am testing v0.5.0 before I `npm publish`
I am not seeing the expected behavior of msg.twcparams.precision overriding the node edit properties.
Holding on the release until I can debug some more.

**Comment by johnwalicki** [comment]
I've got a fix.

**Comment by johnwalicki** [comment]
node-red-contrib-twc-weather:0.5.0 is available on npm
- https://flows.nodered.org/node/node-red-contrib-twc-weather
- https://www.npmjs.com/package/node-red-contrib-twc-weather

**Comment by jimison** [comment]
Up and running. 😎

**Pull request merged**
